# Generated by Django 5.0.7 on 2024-08-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0002_rename_article_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='content',
        ),
        migrations.AddField(
            model_name='memo',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
