# Generated by Django 5.1.3 on 2024-11-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0003_remove_memo_content_memo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
