# Generated by Django 5.1 on 2024-08-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0004_memo_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='chat_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
