# Generated by Django 5.1.4 on 2024-12-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=255, verbose_name='チャット部屋名'),
        ),
    ]
