# Generated by Django 5.1.3 on 2024-12-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_consultation_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='checklist',
            field=models.JSONField(blank=True, null=True, verbose_name='質問項目'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='書類'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='document',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
