# Generated by Django 5.1.3 on 2024-12-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_consultation_checklist_alter_consultation_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='room_name',
        ),
        migrations.AddField(
            model_name='consultation',
            name='room_link',
            field=models.URLField(default='sample', verbose_name='チャット名'),
            preserve_default=False,
        ),
    ]
