version: '3.8'

services:
  django:
    build: ./django
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    # 以下はdaphneを使う場合
    # command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    expose:
      - 8000
    volumes:
      - ./src:/code
    depends_on:
      - db
  # FastAPI用
  fastapi:
    build: ./fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    expose:
      - 8001
    volumes:
      - ./fastapi:/code
  db:
    image: postgres:15.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=iniad
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/collected_static:/static
    depends_on:
      - django
      - fastapi
volumes:
  postgres-data: