version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    volumes:
      - .:/code
    env_file:
      - ./src/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.1
    build:
      context: ./pgvector
      dockerfile: Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./src/.env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/collected_static:/code/src/collected_static
      - ./src/media:/code/src/media
    depends_on:
      - django

volumes:
  postgres-data:
