version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    volumes:
      - .:/code
    env_file:
      - ./src/.env
    depends_on:
      - db

  db:
    image: postgres:16.1
    build:
      context: ./pgvector
      dockerfile: Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./src/.env

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/collected_static:/code/src/collected_static
    depends_on:
      - django

volumes:
  postgres-data:
