name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # ランナーを ubuntu-22.04 に指定
    runs-on: ubuntu-22.04

    steps:
      # 1. ソースコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. ソースコードを本番サーバーに転送
      - name: Copy project to server
        uses: appleboy/scp-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./"
          target: "/root/rent_checker"

      # 3. 本番サーバーで Docker をビルドしてデプロイ
      - name: Build and Deploy on Server
        uses: appleboy/ssh-action@v0.1.18
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # デプロイ用ディレクトリへ移動
            cd /root/rent_checker

            # Docker イメージをビルド
            docker compose down
            docker compose build

            # コンテナを再起動
            docker compose up -d
